import { AnimatePresence, motion } from 'framer-motion';
import { AlertCircle } from 'lucide-react';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { io } from 'socket.io-client';
import { FilterCard } from '../components/dashboard/FilterCard';
import { Navbar } from '../components/dashboard/Navbar';
import { SummaryCard } from '../components/dashboard/SummaryCard';
import { IncidentMap } from '../components/map/IncidentMap';
import { DetailSheet } from '../components/reports/DetailSheet';
import { ReportList } from '../components/reports/ReportList';
import { PasswordDialog } from '../components/settings/PasswordDialog';
import { SettingsDialog } from '../components/settings/SettingsDialog';
import { api, getMe, getReport, getReports, getSettings, getStats } from '../lib/api';
import type { DetailResponse, ReportSummary, Settings, Stats, User } from '../types';

const emptyStats: Stats = { total: 0, today: 0, active: 0, critical: 0 };
export default function App() {
  const [user,setUser] = useState<User | null>(null); const [settings,setSettings] = useState<Settings>({ app_title:'D DRONE', app_logo_path:'' }); const [stats,setStats] = useState(emptyStats); const [reports,setReports] = useState<ReportSummary[]>([]); const [selectedId,setSelectedId] = useState<number | null>(null); const [detail,setDetail] = useState<DetailResponse | null>(null); const [loading,setLoading] = useState(true); const [detailLoading,setDetailLoading] = useState(false); const [search,setSearch] = useState(''); const [debouncedSearch,setDebouncedSearch] = useState(''); const [severity,setSeverity] = useState(''); const [status,setStatus] = useState(''); const [settingsOpen,setSettingsOpen] = useState(false); const [passwordOpen,setPasswordOpen] = useState(false); const [toast,setToast] = useState(''); const [fatal,setFatal] = useState('');
  const notify = useCallback((message: string) => { setToast(message); window.setTimeout(() => setToast(''), 2800); }, []);
  const query = useMemo(() => { const value = new URLSearchParams(); if (debouncedSearch) value.set('search',debouncedSearch); if (severity) value.set('severity',severity); if (status) value.set('status',status); return value; }, [debouncedSearch,severity,status]);
  const loadReports = useCallback(async () => { const rows = await getReports(query); setReports(rows); }, [query]);
  const refresh = useCallback(async () => { try { const [rows,nextStats] = await Promise.all([getReports(query),getStats()]); setReports(rows); setStats(nextStats); } catch (e) { notify(e instanceof Error ? e.message : 'โหลดข้อมูลไม่สำเร็จ'); } }, [query,notify]);
  useEffect(() => { const timer = window.setTimeout(() => setDebouncedSearch(search.trim()), 280); return () => window.clearTimeout(timer); }, [search]);
  useEffect(() => { (async () => { try { const me = await getMe(); if (!me.user) { window.location.href='/login/'; return; } setUser(me.user); const [nextSettings,nextStats,rows] = await Promise.all([getSettings(),getStats(),getReports(new URLSearchParams())]); setSettings(nextSettings); setStats(nextStats); setReports(rows); document.title = `${nextSettings.app_title || 'D DRONE'} · ศูนย์บัญชาการ`; } catch (e) { setFatal(e instanceof Error ? e.message : 'เปิดศูนย์บัญชาการไม่สำเร็จ'); } finally { setLoading(false); } })(); }, []);
  useEffect(() => { if (!loading) loadReports().catch((e) => notify(e.message)); }, [query,loading,loadReports,notify]);
  useEffect(() => { if (!user) return; const socket = io(); socket.on('report:new', async () => { notify('มีรายงานเหตุใหม่'); await refresh(); }); socket.on('report:updated', async (event) => { await refresh(); if (selectedId === Number(event.id)) { const next = await getReport(Number(event.id)); setDetail(next); } }); return () => { socket.disconnect(); }; }, [user,refresh,selectedId,notify]);
  async function selectReport(report: ReportSummary) { setSelectedId(report.id); setDetailLoading(true); try { setDetail(await getReport(report.id)); } catch (e) { notify(e instanceof Error ? e.message : 'โหลดรายละเอียดไม่สำเร็จ'); } finally { setDetailLoading(false); } }
  async function saveState(nextStatus: string, nextSeverity: string) { if (!selectedId || !detail) return; const body: Record<string,string> = {}; if (nextStatus !== detail.report.status) body.status=nextStatus; if (nextSeverity !== (detail.report.operator_severity || detail.report.reporter_severity)) body.operatorSeverity=nextSeverity; if (!Object.keys(body).length) return notify('ยังไม่มีข้อมูลที่เปลี่ยนแปลง'); await api(`/api/admin/reports/${selectedId}`, { method:'PATCH', headers:{'Content-Type':'application/json'}, body:JSON.stringify(body) }); setDetail(await getReport(selectedId)); await refresh(); notify('บันทึกข้อมูลเหตุเรียบร้อย'); }
  async function addNote(note: string) { if (!selectedId) return; await api(`/api/admin/reports/${selectedId}/notes`, { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({note}) }); setDetail(await getReport(selectedId)); notify('เพิ่มหมายเหตุเรียบร้อย'); }
  async function saveSettings(form: FormData) { const next = await api<Settings>('/api/admin/settings',{method:'POST',body:form}); setSettings(next); document.title=`${next.app_title} · ศูนย์บัญชาการ`; notify('บันทึกชื่อและโลโก้เรียบร้อย'); }
  async function logout() { await fetch('/api/auth/logout',{method:'POST'}); window.location.href='/login/'; }
  if (loading) return <div className="grid h-screen place-items-center bg-slate-50 text-sm text-muted"><span className="flex items-center gap-3"><i className="loading-dot" />กำลังเปิดศูนย์บัญชาการ...</span></div>;
  if (fatal || !user) return <div className="grid h-screen place-items-center bg-slate-50"><div className="text-center text-sm text-red-600"><AlertCircle className="mx-auto mb-2" />{fatal || 'ไม่พบบัญชีผู้ใช้'}</div></div>;
  return <main className="relative h-screen w-screen overflow-hidden bg-slate-200"><IncidentMap reports={reports} selectedId={selectedId} onSelect={selectReport} /><Navbar user={user} settings={settings} search={search} onSearch={setSearch} onRefresh={refresh} onSettings={() => setSettingsOpen(true)} onPassword={() => setPasswordOpen(true)} onLogout={logout} /><div className="pointer-events-none fixed bottom-4 left-4 top-[92px] z-[800] flex w-[350px] max-w-[calc(100vw-32px)] flex-col gap-3"><div className="pointer-events-auto"><SummaryCard stats={stats} /></div><div className="pointer-events-auto"><FilterCard severity={severity} status={status} onSeverity={setSeverity} onStatus={setStatus} onClear={() => { setSeverity(''); setStatus(''); }} /></div><div className="pointer-events-auto flex min-h-0 flex-1"><ReportList reports={reports} selectedId={selectedId} loading={loading} onSelect={selectReport} /></div></div><div className="glass fixed bottom-4 left-[382px] z-[700] hidden items-center gap-3 rounded-xl px-3 py-2 text-[9px] text-slate-600 sm:flex"><span><i className="legend bg-red-500" />วิกฤต</span><span><i className="legend bg-orange-500" />สูง</span><span><i className="legend bg-amber-400" />ปานกลาง</span><span><i className="legend bg-sky-600" />ต่ำ</span></div><DetailSheet open={selectedId !== null} data={detail} loading={detailLoading} role={user.role} onClose={() => {setSelectedId(null);setDetail(null);}} onSave={saveState} onNote={addNote} /><SettingsDialog open={settingsOpen} settings={settings} onOpenChange={setSettingsOpen} onSave={saveSettings} /><PasswordDialog open={passwordOpen} onOpenChange={setPasswordOpen} onSuccess={() => notify('เปลี่ยนรหัสผ่านเรียบร้อย')} /><AnimatePresence>{toast && <motion.div initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} exit={{opacity:0,y:8}} className="fixed bottom-5 right-5 z-[5000] rounded-xl bg-slate-900 px-4 py-3 text-xs text-white shadow-2xl">{toast}</motion.div>}</AnimatePresence></main>;
}
