import { AnimatePresence, motion } from 'framer-motion';
import { AlertCircle } from 'lucide-react';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { io } from 'socket.io-client';
import { FilterCard } from '../components/dashboard/FilterCard';
import { Navbar } from '../components/dashboard/Navbar';
import { SummaryCard } from '../components/dashboard/SummaryCard';
import { IncidentMap } from '../components/map/IncidentMap';
import { DetailSheet } from '../components/reports/DetailSheet';
import { ReportList } from '../components/reports/ReportList';
import { PasswordDialog } from '../components/settings/PasswordDialog';
import { SettingsDialog } from '../components/settings/SettingsDialog';
import { api, getMe, getNotifications, getReport, getReports, getSettings, getStats, markAllRead, markRead } from '../lib/api';
import type { DetailResponse, ReportSummary, Settings, Stats, User } from '../types';

const emptyStats: Stats = { total: 0, today: 0, active: 0, critical: 0 };
const defaultSettings: Settings = { app_title:'D DRONE', organization_name:'ศูนย์ควบคุมและเฝ้าระวังอากาศยาน', app_logo_path:'', secondary_logo_path:'' };
export default function App() {
  const [user,setUser] = useState<User | null>(null), [settings,setSettings] = useState<Settings>(defaultSettings), [stats,setStats] = useState(emptyStats), [reports,setReports] = useState<ReportSummary[]>([]), [unread,setUnread] = useState<ReportSummary[]>([]), [selectedId,setSelectedId] = useState<number | null>(null), [detail,setDetail] = useState<DetailResponse | null>(null), [loading,setLoading] = useState(true), [detailLoading,setDetailLoading] = useState(false), [search,setSearch] = useState(''), [debouncedSearch,setDebouncedSearch] = useState(''), [severity,setSeverity] = useState(''), [status,setStatus] = useState(''), [historyMode,setHistoryMode] = useState(false), [settingsOpen,setSettingsOpen] = useState(false), [passwordOpen,setPasswordOpen] = useState(false), [toast,setToast] = useState(''), [fatal,setFatal] = useState('');
  const [isDark,setIsDark] = useState(() => localStorage.getItem('ddrone-theme') ? localStorage.getItem('ddrone-theme') === 'dark' : window.matchMedia('(prefers-color-scheme: dark)').matches);
  const notify = useCallback((message: string) => { setToast(message); window.setTimeout(() => setToast(''), 2800); }, []);
  const query = useMemo(() => { const p=new URLSearchParams(); p.set('scope',historyMode?'history':'active'); if(debouncedSearch)p.set('search',debouncedSearch);if(severity)p.set('severity',severity);if(status)p.set('status',status);return p; },[historyMode,debouncedSearch,severity,status]);
  const refresh = useCallback(async () => { try { const [rows,nextStats,notifications] = await Promise.all([getReports(query),getStats(),getNotifications()]); setReports(rows); setStats(nextStats); setUnread(notifications.reports); } catch(e){notify(e instanceof Error?e.message:'โหลดข้อมูลไม่สำเร็จ');} },[query,notify]);
  useEffect(()=>{document.documentElement.classList.toggle('dark',isDark);localStorage.setItem('ddrone-theme',isDark?'dark':'light');},[isDark]);
  useEffect(()=>{const timer=window.setTimeout(()=>setDebouncedSearch(search.trim()),280);return()=>window.clearTimeout(timer)},[search]);
  useEffect(()=>{(async()=>{try{const me=await getMe();if(!me.user){window.location.href='/login/';return;}setUser(me.user);const [nextSettings,nextStats,rows,notifications]=await Promise.all([getSettings(),getStats(),getReports(new URLSearchParams('scope=active')),getNotifications()]);setSettings(nextSettings);setStats(nextStats);setReports(rows);setUnread(notifications.reports);document.title=`${nextSettings.app_title||'D DRONE'} · ศูนย์บัญชาการ`;}catch(e){setFatal(e instanceof Error?e.message:'เปิดศูนย์บัญชาการไม่สำเร็จ');}finally{setLoading(false);}})()},[]);
  useEffect(()=>{if(!loading)refresh()},[query,loading,refresh]);
  useEffect(()=>{if(!user)return;const socket=io();socket.on('report:new',async()=>{notify('มีรายงานเหตุใหม่');await refresh();});socket.on('report:updated',async(event)=>{await refresh();if(selectedId===Number(event.id))setDetail(await getReport(Number(event.id)));});return()=>{socket.disconnect()}},[user,refresh,selectedId,notify]);
  async function selectReport(report:ReportSummary){setSelectedId(report.id);setDetailLoading(true);try{const data=await getReport(report.id);setDetail(data);if(report.is_unread){await markRead(report.id);setUnread((items)=>items.filter((item)=>item.id!==report.id));setReports((items)=>items.map((item)=>item.id===report.id?{...item,is_unread:false}:item));}}catch(e){notify(e instanceof Error?e.message:'โหลดรายละเอียดไม่สำเร็จ')}finally{setDetailLoading(false)}}
  async function saveState(nextStatus:string,nextSeverity:string){if(!selectedId||!detail)return;const body:Record<string,string>={};if(nextStatus!==detail.report.status)body.status=nextStatus;if(nextSeverity!==(detail.report.operator_severity||detail.report.reporter_severity))body.operatorSeverity=nextSeverity;if(!Object.keys(body).length)return notify('ยังไม่มีข้อมูลที่เปลี่ยนแปลง');await api(`/api/admin/reports/${selectedId}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});setDetail(await getReport(selectedId));await refresh();notify('บันทึกข้อมูลเหตุเรียบร้อย')}
  async function complete(){if(!selectedId)return;await api(`/api/admin/reports/${selectedId}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:'RESOLVED'})});setSelectedId(null);setDetail(null);await refresh();notify('ย้ายเหตุไปยังเหตุการณ์ย้อนหลังแล้ว')}
  async function addNote(note:string){if(!selectedId)return;await api(`/api/admin/reports/${selectedId}/notes`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({note})});setDetail(await getReport(selectedId));notify('เพิ่มหมายเหตุเรียบร้อย')}
  async function saveSettings(form:FormData){const next=await api<Settings>('/api/admin/settings',{method:'POST',body:form});setSettings(next);document.title=`${next.app_title} · ศูนย์บัญชาการ`;notify('บันทึก Branding เรียบร้อย')}
  async function readAll(){await markAllRead();setUnread([]);setReports((items)=>items.map((item)=>({...item,is_unread:false})));notify('ทำเครื่องหมายว่าอ่านทั้งหมดแล้ว')}
  async function logout(){await fetch('/api/auth/logout',{method:'POST'});window.location.href='/login/'}
  const switchHistory=()=>{setHistoryMode((current)=>!current);setSelectedId(null);setDetail(null);setStatus('');};
  if(loading)return <div className="grid h-screen place-items-center bg-slate-50 text-sm text-muted"><span className="flex items-center gap-3"><i className="loading-dot"/>กำลังเปิดศูนย์บัญชาการ...</span></div>;
  if(fatal||!user)return <div className="grid h-screen place-items-center bg-slate-50"><div className="text-center text-sm text-red-600"><AlertCircle className="mx-auto mb-2"/>{fatal||'ไม่พบบัญชีผู้ใช้'}</div></div>;
  return <main className="relative h-screen w-screen overflow-hidden bg-slate-200 dark:bg-slate-950"><IncidentMap reports={historyMode?[]:reports} selectedId={selectedId} onSelect={selectReport} isDark={isDark}/>{historyMode&&<div className="pointer-events-none absolute inset-0 z-[500] grid place-items-center"><span className="rounded-full bg-slate-900/70 px-4 py-2 text-xs text-white">โหมดเหตุการณ์ย้อนหลัง · ไม่แสดงหมุดบนแผนที่</span></div>}<Navbar user={user} settings={settings} search={search} unread={unread} isDark={isDark} historyMode={historyMode} onSearch={setSearch} onRefresh={refresh} onSettings={()=>setSettingsOpen(true)} onPassword={()=>setPasswordOpen(true)} onLogout={logout} onTheme={()=>setIsDark((current)=>!current)} onHistory={switchHistory} onNotification={selectReport} onReadAll={readAll}/><div className="pointer-events-none fixed bottom-4 left-4 top-[92px] z-[800] flex w-[350px] max-w-[calc(100vw-32px)] flex-col gap-3"><div className="pointer-events-auto"><SummaryCard stats={stats}/></div><div className="pointer-events-auto"><FilterCard severity={severity} status={status} onSeverity={setSeverity} onStatus={setStatus} onClear={()=>{setSeverity('');setStatus('')}}/></div><div className="pointer-events-auto flex min-h-0 flex-1"><ReportList reports={reports} selectedId={selectedId} loading={loading} historyMode={historyMode} onSelect={selectReport}/></div></div><DetailSheet open={selectedId!==null} data={detail} loading={detailLoading} role={user.role} onClose={()=>{setSelectedId(null);setDetail(null)}} onSave={saveState} onNote={addNote} onComplete={complete}/><SettingsDialog open={settingsOpen} settings={settings} onOpenChange={setSettingsOpen} onSave={saveSettings}/><PasswordDialog open={passwordOpen} onOpenChange={setPasswordOpen} onSuccess={()=>notify('เปลี่ยนรหัสผ่านเรียบร้อย')}/><AnimatePresence>{toast&&<motion.div initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} exit={{opacity:0,y:8}} className="fixed bottom-5 right-5 z-[5000] rounded-xl bg-slate-900 px-4 py-3 text-xs text-white shadow-2xl">{toast}</motion.div>}</AnimatePresence></main>;
}
