import { Image, Upload } from 'lucide-react';
import { useEffect, useState } from 'react';
import type { Settings } from '../../types';
import { Button } from '../ui/button';
import { Dialog, DialogContent, DialogDescription, DialogTitle } from '../ui/dialog';
import { Input } from '../ui/input';

export function SettingsDialog({ open, settings, onOpenChange, onSave }: { open: boolean; settings: Settings; onOpenChange: (open: boolean) => void; onSave: (form: FormData) => Promise<void> }) {
  const [title,setTitle]=useState(settings.app_title),[organization,setOrganization]=useState(settings.organization_name),[primary,setPrimary]=useState<File|null>(null),[secondary,setSecondary]=useState<File|null>(null),[primaryPreview,setPrimaryPreview]=useState(''),[secondaryPreview,setSecondaryPreview]=useState(''),[error,setError]=useState(''),[saving,setSaving]=useState(false);
  useEffect(()=>{setTitle(settings.app_title||'D DRONE');setOrganization(settings.organization_name||'');setPrimary(null);setSecondary(null);setPrimaryPreview(settings.app_logo_path?`/uploads/${settings.app_logo_path}`:'');setSecondaryPreview(settings.secondary_logo_path?`/uploads/${settings.secondary_logo_path}`:'');setError('')},[settings,open]);
  const choose=(file:File|null,kind:'primary'|'secondary')=>{if(kind==='primary'){setPrimary(file);if(file)setPrimaryPreview(URL.createObjectURL(file));}else{setSecondary(file);if(file)setSecondaryPreview(URL.createObjectURL(file));}};
  async function submit(e:React.FormEvent){e.preventDefault();if(!title.trim())return setError('กรุณาระบุชื่อโครงการ');const form=new FormData();form.set('appTitle',title.trim());form.set('organizationName',organization.trim());if(primary)form.set('logo',primary);if(secondary)form.set('secondaryLogo',secondary);setSaving(true);setError('');try{await onSave(form);onOpenChange(false)}catch(e){setError(e instanceof Error?e.message:'บันทึกไม่สำเร็จ')}finally{setSaving(false)}}
  const logoPicker=(label:string,preview:string,kind:'primary'|'secondary')=><label className="mt-4 block text-[11px] font-semibold">{label}<span className="ml-1 font-normal text-muted">PNG, JPG, WEBP หรือ GIF ไม่เกิน 2 MB</span><span className="mt-1.5 flex cursor-pointer items-center gap-3 rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-3"><span className="grid h-14 w-14 place-items-center overflow-hidden rounded-2xl bg-blue-500 text-white">{preview?<img className="h-full w-full object-cover" src={preview} alt={label}/>:<Image size={20}/>}</span><span className="text-xs font-medium text-slate-600"><Upload className="mb-1" size={15}/>เลือกไฟล์ {label}</span><input type="file" accept="image/png,image/jpeg,image/webp,image/gif" className="sr-only" onChange={(e)=>choose(e.target.files?.[0]||null,kind)}/></span></label>;
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogTitle>ตั้งค่า Branding</DialogTitle><DialogDescription>ชื่อ หน่วยงาน และโลโก้คู่จะแสดงในแถบนำทาง</DialogDescription><form onSubmit={submit} className="mt-5"><label className="text-[11px] font-semibold">ชื่อโครงการ<Input className="mt-1.5" value={title} maxLength={100} onChange={(e)=>setTitle(e.target.value)}/></label><label className="mt-3 block text-[11px] font-semibold">ชื่อหน่วยงาน / คำอธิบาย<Input className="mt-1.5" value={organization} maxLength={160} onChange={(e)=>setOrganization(e.target.value)}/></label>{logoPicker('โลโก้ระบบ',primaryPreview,'primary')}{logoPicker('โลโก้หน่วยงาน',secondaryPreview,'secondary')}{error&&<p className="mt-3 rounded-xl bg-red-50 p-2.5 text-[10px] text-red-600">{error}</p>}<Button disabled={saving} className="mt-4 w-full" type="submit">{saving?'กำลังบันทึก...':'บันทึกการตั้งค่า'}</Button></form></DialogContent></Dialog>;
}
